### Base url
GET {{base}}

### Create item
POST {{base}}/items
Content-Type: application/json

{
  "name": "hello",
  "description": "Just a hello"
}

### Get items
GET {{base}}/items

### Get item
GET {{base}}/items/whz9wd7hjo01us8pjycm5xie

### Create observation
POST {{base}}/items/{id}/observations
Content-Type: application/json

{
  "start": "2025-01-01T00:00:02Z",
  "end": "2025-01-01T00:00:58Z"
}
