### Create item
POST {{base}}/items
Content-Type: application/json

{
  "name": "{{$random.hacker.noun}}",
  "description": "{{$random.lorem.sentence}}"
}

> {% client.global.set("item_id", response.body.id); %}

### Get item
GET {{base}}/items/{{item_id}}

### Get items
GET {{base}}/items

### Create observation
POST {{base}}/items/{{item_id}}/observations
Content-Type: application/json

{
  "start": "2025-01-01T00:00:02Z",
  "end": "2025-01-01T00:00:58Z"
}
